version: "2"

services:
  redis:
    image: redis
    expose: ["6379"]

  db:
    image: postgres:9.4

  voting-app:
    image: $DTR/voting-app:$GIT_COMMIT
    ports:
      - "5000:80"

  result-app:
    image: $DTR/result-app:$GIT_COMMIT
    ports:
      - "5001:80"

  worker:
    image: $DTR/worker:$GIT_COMMIT
